spring:
  application:
    name: beans-loyalty
  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?authSource=admin
      database: loyaltyeventstore
    redis:
      host: ${REDIS_HOST:loyalty-redis-svc}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  logging:
    level:
      org.springframework.data.mongodb.core: DEBUG
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: beans-loyalty-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

loyalty:
  bonus-percentage: ${LOYALTY_BONUS_PERCENTAGE}

server:
  port: 8004